### ISSUE TITLE
Footer: social buttons a bit close + strange outline around cityscape

### ISSUE THREAD

**Issue by justinkemerling** [jakewelchert/dcd#10]
![screen shot 2017-03-30 at 11 24 36 am](https://cloud.githubusercontent.com/assets/5384728/24514981/b913d9ac-153b-11e7-9ba2-3f43459ce19b.png)

![screen shot 2017-03-30 at 11 26 03 am](https://cloud.githubusercontent.com/assets/5384728/24514982/b9281232-153b-11e7-8c09-efb9cfad8c7b.png)

**Comment by jakewelchert** [comment]
Updated for review.

**Comment by jakewelchert** [comment]
Updated for review.
