### ISSUE TITLE
Footer: w/ cityscape click, can you zoom to the top?

### ISSUE THREAD

**Issue by justinkemerling** [jakewelchert/dcd#11]
Rather than just landing at the top. Like a fast reverse scroll.

**Comment by jakewelchert** [comment]
Updated for review.

**Comment by justinkemerling** [comment]
This is sweet. Can we do it on all pages?

**Comment by jakewelchert** [comment]
You might need to just refresh your page for this. If you come across a page that it's not updated on let me know.

**Comment by justinkemerling** [comment]
It looks like News, Events, and Get Involved are incorrect as of now. The spacing is off w/ the basic footer copy. 

![screen shot 2017-04-04 at 1 01 32 pm](https://cloud.githubusercontent.com/assets/5384728/24671360/ddd2ea18-1936-11e7-9717-4ebeb5707540.png)

**Comment by jakewelchert** [comment]
Thanks. Updated those pages for review.
