### ISSUE TITLE
Spacing: adjust for consistency w/ text and padding

### ISSUE THREAD

**Issue by justinkemerling** [jakewelchert/dcd#12]
1. Space between the line and text is good in the Events part.
2. Space between text and the next section is good in the News part.

![screen shot 2017-03-30 at 11 29 13 am](https://cloud.githubusercontent.com/assets/5384728/24515146/4cf8ae36-153c-11e7-98bb-2bcb03fe567e.png)
![screen shot 2017-03-30 at 11 29 17 am](https://cloud.githubusercontent.com/assets/5384728/24515147/4d0da3ae-153c-11e7-84b8-2adddcd9a00e.png)

**Comment by jakewelchert** [comment]
Updated for review.
