### ISSUE TITLE
Logo: bottom of the letters getting cut off (minor)

### ISSUE THREAD

**Issue by justinkemerling** [jakewelchert/dcd#13]
Just a sliver. More noticeable on Retina.

![screen shot 2017-03-30 at 11 24 06 am](https://cloud.githubusercontent.com/assets/5384728/24515191/68aba71e-153c-11e7-9799-878acd02d57e.png)

**Comment by jakewelchert** [comment]
Issue with SVG. Can you review this and let me know if it's good on your end?

**Comment by justinkemerling** [comment]
Good on my end.
