### ISSUE TITLE
Type: increase spacing between subheads and paragraphs

### ISSUE THREAD

**Issue by justinkemerling** [jakewelchert/dcd#14]
Mockup attached. Maybe we try the 'Light' text weight for body copy?

![screen shot 2017-03-30 at 11 33 38 am](https://cloud.githubusercontent.com/assets/5384728/24516337/e18f11f4-153f-11e7-8499-6655a07bd300.png)

**Comment by jakewelchert** [comment]
Updated for review. Maybe it's best if we quick look over type tomorrow to clarify on sizes.

**Comment by jakewelchert** [comment]
Updated for review. Overall type size is a bit smaller in browser than InVision. How's it feeling for you? I can increase size no problem, just thought it was a little big when there's more copy like this.

**Comment by justinkemerling** [comment]
Indeed. This is looking good.
