### ISSUE TITLE
Mobile: include social media links w/ full nav

### ISSUE THREAD

**Issue by justinkemerling** [jakewelchert/dcd#15]
I think the rule should be as long as the navigation is visible, the social media links should be good. Maybe they go right under the Donate Now button.

![screen shot 2017-03-30 at 11 57 01 am](https://cloud.githubusercontent.com/assets/5384728/24516424/1dc5a02a-1540-11e7-9921-a7bcc8c78c5d.png)

**Comment by jakewelchert** [comment]
Updated for review.

**Comment by justinkemerling** [comment]
Yeah man, nice. A bit of overlap w/ the Donate Now button but otherwise good.

![screen shot 2017-04-01 at 10 54 27 am](https://cloud.githubusercontent.com/assets/5384728/24580197/a32f5730-16c9-11e7-8854-319969cd1895.png)

**Comment by jakewelchert** [comment]
Updated for review.

**Comment by justinkemerling** [comment]
Still a little weird w/ the nav. Would be ideal to have the social buttons fit on the same line as the Donate Button when able 1024 iPad width. The nav text links are also breaking down in this Safari view.

![screen shot 2017-04-03 at 9 24 53 am](https://cloud.githubusercontent.com/assets/5384728/24614015/9c912a8e-184f-11e7-9a2e-599abf3d1f83.png)

**Comment by jakewelchert** [comment]
Updated for review.

**Comment by justinkemerling** [comment]
Safari is looking wonky still. 

![screen shot 2017-04-05 at 9 01 10 am](https://cloud.githubusercontent.com/assets/5384728/24709122/8ab082c0-19de-11e7-96a7-82e954efe2c3.png)
![screen shot 2017-04-05 at 9 01 39 am](https://cloud.githubusercontent.com/assets/5384728/24709123/8abb4d72-19de-11e7-9907-90b94e43d2d4.png)

**Comment by jakewelchert** [comment]
Updated for review.
