### ISSUE TITLE
Links: add text link for all post headers/headlines and images associated with each post

### ISSUE THREAD

**Issue by justinkemerling** [jakewelchert/dcd#16]
Includes:
News
Events
People

![screen shot 2017-03-30 at 12 01 26 pm](https://cloud.githubusercontent.com/assets/5384728/24516528/a023a792-1540-11e7-9c08-039edb1f88bf.png)
![screen shot 2017-03-30 at 12 01 22 pm](https://cloud.githubusercontent.com/assets/5384728/24516527/a020e87c-1540-11e7-95e1-b4ae80673a5f.png)

**Comment by jakewelchert** [comment]
Updated for review.

**Comment by justinkemerling** [comment]
Also needed for Upcoming Events

![screen shot 2017-04-01 at 10 55 42 am](https://cloud.githubusercontent.com/assets/5384728/24580205/cb79cd74-16c9-11e7-8d22-c0efef280f38.png)

**Comment by jakewelchert** [comment]
Added to meeting title, but wondering if the date needs a link, as well as the address, time? Or, does the address actually link to Google address? Also, if we link the time, what does that pull up?

**Comment by justinkemerling** [comment]
The addresses linking to Google would be cool. I like linking the date too whatever the detail page is. Just like the title. We don't need to link the time.

**Comment by jakewelchert** [comment]
Resolved.
