### ISSUE TITLE
Mobile: I think we'll need type sizes to go a little smaller on mobile

### ISSUE THREAD

**Issue by justinkemerling** [jakewelchert/dcd#19]
Feels a little big on the phone size:

![screen shot 2017-03-30 at 12 05 04 pm](https://cloud.githubusercontent.com/assets/5384728/24516702/3719b10a-1541-11e7-91f0-0cd76ec71a88.png)
![screen shot 2017-03-30 at 12 05 17 pm](https://cloud.githubusercontent.com/assets/5384728/24516701/3717dda8-1541-11e7-882a-5fd7d90b9d8c.png)

**Comment by jakewelchert** [comment]
Updated for review.

**Comment by justinkemerling** [comment]
Type is looking good. Probably a little smaller on those buttons too. 

![screen shot 2017-04-01 at 11 00 54 am](https://cloud.githubusercontent.com/assets/5384728/24580250/7ef0218c-16ca-11e7-8be9-9728cab3a9ad.png)

**Comment by jakewelchert** [comment]
Updated for review.
