### ISSUE TITLE
Heading Tags H2 and H3

### ISSUE THREAD

**Issue by justinkemerling** [jakewelchert/dcd#22]
Referencing: https://invis.io/G3A82BLS7#/217699488_JKDC_DCD-Website_SiteDesign_DETAIL-News

While keeping the News listing the H3, can the page titles and homepage tagline be in H2?

![screen shot 2017-04-01 at 11 03 00 am](https://cloud.githubusercontent.com/assets/5384728/24580278/ea91604a-16ca-11e7-804b-77510cc87ca8.png)

**Comment by jakewelchert** [comment]
Updated for review.
