### ISSUE TITLE
Photo Row: on the homepage the image is repeating

### ISSUE THREAD

**Issue by justinkemerling** [jakewelchert/dcd#24]
I like how this looks. Just have a repeating image.

![screen shot 2017-04-05 at 9 03 46 am](https://cloud.githubusercontent.com/assets/5384728/24709252/e876973c-19de-11e7-838c-0ba18d9259f8.png)

**Comment by jakewelchert** [comment]
Think we should just do crops of the original images? It would be saving out an additional image, or using Wordpress to crop a thumbnail. Maybe worth talking to Alex about. Although...he did say maybe we avoid giving them the power to update that?

**Comment by jakewelchert** [comment]
Resolved.
