### ISSUE TITLE
Home: left align event info

### ISSUE THREAD

**Issue by justinkemerling** [jakewelchert/dcd#28]
<img width="714" alt="screen shot 2017-06-26 at 2 50 52 pm" src="https://user-images.githubusercontent.com/5384728/27558059-7e092ec6-5a81-11e7-9e57-767149b4aad2.png">

**Comment by jakewelchert** [comment]
Added minimum width to column. To update, overwrite the **index.css** file.

**Comment by alexpgates** [comment]
Updated!
