### ISSUE TITLE
Posts: add underline for link text

### ISSUE THREAD

**Issue by justinkemerling** [jakewelchert/dcd#30]
Keep hover state as red

<img width="456" alt="screen shot 2017-06-26 at 2 52 09 pm" src="https://user-images.githubusercontent.com/5384728/27558174-0331790a-5a82-11e7-9655-10c4bc6a00e4.png">

**Comment by jakewelchert** [comment]
Update **body.css**

**Comment by alexpgates** [comment]
Updated!
