### ISSUE TITLE
Candidates/Officials: finesse spacing for description copy and individual tiles

### ISSUE THREAD

**Issue by justinkemerling** [jakewelchert/dcd#32]
<img width="1205" alt="screen shot 2017-06-26 at 2 52 56 pm" src="https://user-images.githubusercontent.com/5384728/27558279-71dc1d24-5a82-11e7-856d-858cce596e82.png">
<img width="1225" alt="screen shot 2017-06-26 at 2 52 49 pm" src="https://user-images.githubusercontent.com/5384728/27558280-73673c00-5a82-11e7-870f-770e513320b4.png">

**Comment by jakewelchert** [comment]
1. Change **class='candidates-subhead'** on the H5 to **class='candidates-subhead-h5'**
2. Upload and overwrite candidates.css

**Comment by alexpgates** [comment]
Updated!

Note: there are a few other places where we're using candidates-subhead on h5's. 
I **only** changed this class in this particular section for candidates and elected officials.
