### ISSUE TITLE
Candidates/Officials: Spacing issue w/ offices that go to 2 lines 

### ISSUE THREAD

**Issue by justinkemerling** [jakewelchert/dcd#34]
<img width="853" alt="screen shot 2017-06-26 at 3 34 16 pm" src="https://user-images.githubusercontent.com/5384728/27559254-86baad8e-5a85-11e7-85c2-6ae23c01b644.png">

**Comment by jakewelchert** [comment]
Updated the **candidate.css** file and added a top margin to the image

**Comment by alexpgates** [comment]
Updated, but possibly contributing to #36. Maybe.

**Comment by justinkemerling** [comment]
Or maybe this is where the spacing issue happened:

<img width="1345" alt="screen shot 2017-06-29 at 6 45 26 pm" src="https://user-images.githubusercontent.com/5384728/27715200-27dde2ae-5cfb-11e7-83b7-ae45bbc3e2e1.png">

**Comment by alexpgates** [comment]
I think this was fixed in #33
