### ISSUE TITLE
Desired layout for longer titles?

### ISSUE THREAD

**Issue by alexpgates** [jakewelchert/dcd#35]
<img width="510" alt="screenshot 2017-06-29 18 02 58" src="https://user-images.githubusercontent.com/242736/27714231-484b917c-5cf5-11e7-9422-34494e3d6719.png">

Is this the desired layout for candidate blocks that have longer office titles?

**Comment by justinkemerling** [comment]
These should all be snug now:

<img width="684" alt="screen shot 2017-06-29 at 6 48 23 pm" src="https://user-images.githubusercontent.com/5384728/27715260-8e933314-5cfb-11e7-83d7-93f149729663.png">
