### ISSUE TITLE
Single post share spacing

### ISSUE THREAD

**Issue by alexpgates** [jakewelchert/dcd#36]
<img width="1109" alt="screenshot 2017-06-29 18 17 00" src="https://user-images.githubusercontent.com/242736/27714547-2d458a7a-5cf7-11e7-8120-805dbb12ba4c.png">

Something got goofy.

**Comment by justinkemerling** [comment]
Oh yes. This.

**Comment by alexpgates** [comment]
Potentially fixed in #33

**Comment by justinkemerling** [comment]
Good to go.
