### ISSUE TITLE
Missing Favicon

### ISSUE THREAD

**Issue by alexpgates** [jakewelchert/dcd#37]
<img width="117" alt="screenshot 2017-06-29 18 19 06" src="https://user-images.githubusercontent.com/242736/27714602-80a45232-5cf7-11e7-93cd-c554d00bbfdb.png">

**Comment by justinkemerling** [comment]
![dcd_website_favicon](https://user-images.githubusercontent.com/5384728/27715102-883c7616-5cfa-11e7-93c9-fbfe962c6529.png)
This work?

**Comment by alexpgates** [comment]
yeah dog!
