### ISSUE TITLE
Minimum width on events calendar

### ISSUE THREAD

**Issue by jakewelchert** [jakewelchert/dcd#39]
@alexpgates

Fixing alignment here. I made CSS updates to **events-archive.css** so you can update that specific file.

![screen shot 2017-06-30 at 11 16 20 am](https://user-images.githubusercontent.com/3301072/27744626-d5d7b42c-5d85-11e7-9ea1-967a5dbfa54d.png)

**Comment by alexpgates** [comment]
@jakewelchert please give that a hard refresh to see if it looks okay.

**Comment by jakewelchert** [comment]
Looks good to me! Thanks.
