### ISSUE TITLE
WP listing issue?

### ISSUE THREAD

**Issue by justinkemerling** [jakewelchert/dcd#42]
@alexgates

so this seems odd. In the listing view only 5 posts are showing up for me although the numbers of items are complete. In the Candidate example, it should be showing 17. 

![screen shot 2017-06-30 at 12 32 01 pm](https://user-images.githubusercontent.com/5384728/27747349-584a8894-5d90-11e7-894b-5ec748a85b63.png)

**Comment by alexpgates** [comment]
@justinkemerling That's my derp. I was getting fancy with manipulating posts_per_page and didn't consider that this would affect the admin stuff.
Give it a test now - I think I got it.

**Comment by justinkemerling** [comment]
Right on. All good!
